use_frameworks!

platform :ios, '12.0'

target 'CXJAdSDK_Example' do
  pod 'CXJAdSDK', :path => '../'

  target 'CXJAdSDK_Tests' do
    inherit! :search_paths

    
  end
  
  pod 'Toast'
  pod 'MJExtension'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'Masonry'
  
  
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if ['Masonry', 'MBProgressHUD', 'Toast', 'FBRetainCycleDetector', 'MLeaksFinder'].include?(target.name)
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
